### ISSUE TITLE
Using it with Hyper

### ISSUE THREAD

**Issue by prashanthmadi** [joshwnj/electron-run-in-browser#1]
Hi @joshwnj 

Thanks for writing this plugin. I was trying to utilize Hyper https://github.com/zeit/hyper/issues/561 in web app and not sure how to utilize this module in angular2 app. do you have any sample where you utilized this module..

**Comment by joshwnj** [comment]
Thanks @prashanthmadi .  As mentioned in the other thread, it sounds like there is a bit of confusion around what this package does. It's not taking an electron app and running it in the browser, it's just a small helper module for running client-side javascript _within_ an electron app.
